smpl_root_ori_heading_multi_future:
  _target_: isaaclab.managers.ObservationTermCfg
  func: gear_sonic.envs.manager_env.mdp:smpl_root_ori_heading_mf
  params:
    command_name: "motion"
    non_flatten: true
